const fs = require('fs');
const file = 'c:/ProyectosJava/BMP/portal-angular/src/app/features/plataforma/disenador-pantallas/disenador-pantallas.component.ts';
let content = fs.readFileSync(file, 'utf8');

// 1. Sidebar (Search for SIMULADOR button block and append)
content = content.replace(
  /(<button[^>]+click)="addGenericControl\('SIMULADOR'\)"[^>]*>\s*<i[^>]+><\/i>\s*<span[^>]*>Simulador<\/span>\s*<\/button>\s*<\/div>)/,
  `$1\n                  <div class="col-6 mt-2">\n                    <button class="btn btn-outline-secondary btn-control w-100 py-2 d-flex flex-column align-items-center" (click)="addGenericControl('RESUMEN_CASO')">\n                      <i class="bi bi-file-earmark-person fs-5 mb-1 text-secondary"></i>\n                      <span class="lbl-ctrl">Info General</span>\n                    </button>\n                  </div>`
);

// 2. Canvas (Search for SIMULADOR block and append)
content = content.replace(
  /(<div \*ngIf="field\.controlType === 'SIMULADOR'"[\s\S]*?<\/div>)/,
  `$1\n\n                                <!-- RESUMEN_CASO -->\n                                <div *ngIf="field.controlType === 'RESUMEN_CASO'" class="border bg-white rounded-3 shadow-sm mt-2 mb-2">\n                                  <div class="p-2 border-bottom fw-bold text-muted bg-light" style="font-size: 0.85rem;">\n                                    <i class="bi bi-chevron-up me-1"></i> Información General\n                                  </div>\n                                  <div class="p-3">\n                                    <div class="row" style="font-size: 0.75rem;">\n                                      <div class="col-3 text-muted mb-2">FECHA CASO:<br><strong class="text-dark">2026-06-22</strong></div>\n                                      <div class="col-3 text-muted mb-2">NÚMERO CASO:<br><strong class="text-dark">-</strong></div>\n                                      <div class="col-3 text-muted mb-2">CIUDAD:<br><strong class="text-dark">-</strong></div>\n                                      <div class="col-3 text-muted mb-2">AGENCIA:<br><strong class="text-dark">-</strong></div>\n                                      <div class="col-3 text-muted mb-2">ASESOR:<br><strong class="text-dark">-</strong></div>\n                                      <div class="col-3 text-muted mb-2">FECHA SOLICITUD:<br><strong class="text-dark">22/6/2026, 11:32:53 a.m.</strong></div>\n                                      <div class="col-3 text-muted mb-2">SUBSEGMENTO:<br><strong class="text-dark">-</strong></div>\n                                      <div class="col-3 text-muted mb-2">PRODUCTO:<br><strong class="text-dark">VIP</strong></div>\n                                      <div class="col-3 text-muted mb-2">DESTINO COMERCIAL:<br><strong class="text-dark">-</strong></div>\n                                      <div class="col-3 text-muted mb-2">IDENTIFICACIÓN:<br><strong class="text-dark">1700000014</strong></div>\n                                      <div class="col-3 text-muted mb-2">MONTO SOLICITADO:<br><strong class="text-dark">$28,000.00</strong></div>\n                                      <div class="col-3 text-muted mb-2">PLAZO SOLICITADO:<br><strong class="text-dark">200</strong></div>\n                                      <div class="col-3 text-muted">SOLICITANTE:<br><strong class="text-dark">CARLOS ALBERTO PEREZ ORTIZ</strong></div>\n                                      <div class="col-3 text-muted">MONTO APROBADO:<br><strong class="text-dark">-</strong></div>\n                                      <div class="col-3 text-muted">PLAZO APROBADO:<br><strong class="text-dark">-</strong></div>\n                                      <div class="col-3 text-muted">CUOTA DE ENTRADA:<br><strong class="text-dark">-</strong></div>\n                                    </div>\n                                  </div>\n                                </div>`
);

// 3. Preview (Search for OTROS CONTROLES block)
content = content.replace(
  /(<div \*ngIf="field\.controlType !== 'LABEL' && field\.controlType !== 'BUTTON'")/,
  `<!-- RESUMEN_CASO PREVIEW -->\n                          <div *ngIf="field.controlType === 'RESUMEN_CASO'" class="border bg-white rounded-3 shadow-sm mt-2 mb-3">\n                            <div class="p-2 border-bottom fw-bold text-muted bg-light" style="font-size: 0.85rem;">\n                              <i class="bi bi-chevron-up me-1"></i> Información General\n                            </div>\n                            <div class="p-3">\n                              <div class="row" style="font-size: 0.75rem;">\n                                <div class="col-3 text-muted mb-2">FECHA CASO:<br><strong class="text-dark">2026-06-22</strong></div>\n                                <div class="col-3 text-muted mb-2">NÚMERO CASO:<br><strong class="text-dark">-</strong></div>\n                                <div class="col-3 text-muted mb-2">CIUDAD:<br><strong class="text-dark">-</strong></div>\n                                <div class="col-3 text-muted mb-2">AGENCIA:<br><strong class="text-dark">-</strong></div>\n                                <div class="col-3 text-muted mb-2">ASESOR:<br><strong class="text-dark">-</strong></div>\n                                <div class="col-3 text-muted mb-2">FECHA SOLICITUD:<br><strong class="text-dark">22/6/2026, 11:32:53 a.m.</strong></div>\n                                <div class="col-3 text-muted mb-2">SUBSEGMENTO:<br><strong class="text-dark">-</strong></div>\n                                <div class="col-3 text-muted mb-2">PRODUCTO:<br><strong class="text-dark">VIP</strong></div>\n                                <div class="col-3 text-muted mb-2">DESTINO COMERCIAL:<br><strong class="text-dark">-</strong></div>\n                                <div class="col-3 text-muted mb-2">IDENTIFICACIÓN:<br><strong class="text-dark">1700000014</strong></div>\n                                <div class="col-3 text-muted mb-2">MONTO SOLICITADO:<br><strong class="text-dark">$28,000.00</strong></div>\n                                <div class="col-3 text-muted mb-2">PLAZO SOLICITADO:<br><strong class="text-dark">200</strong></div>\n                                <div class="col-3 text-muted">SOLICITANTE:<br><strong class="text-dark">CARLOS ALBERTO PEREZ ORTIZ</strong></div>\n                                <div class="col-3 text-muted">MONTO APROBADO:<br><strong class="text-dark">-</strong></div>\n                                <div class="col-3 text-muted">PLAZO APROBADO:<br><strong class="text-dark">-</strong></div>\n                                <div class="col-3 text-muted">CUOTA DE ENTRADA:<br><strong class="text-dark">-</strong></div>\n                              </div>\n                            </div>\n                          </div>\n\n                          <!-- OTROS CONTROLES -->\n                          $1 && field.controlType !== 'RESUMEN_CASO'`
);

// 4. switch case
content = content.replace(
  /type = 'LINK';\r?\n\s*break;/,
  `type = 'LINK';\n        break;\n      case 'RESUMEN_CASO':\n        label = 'Info General';\n        type = 'RESUMEN_CASO';\n        break;`
);

fs.writeFileSync(file, content, 'utf8');
console.log('Script done.');
