version: '3.8'

services:
  bmp-db:
    image: postgres:15
    container_name: bmp-db
    environment:
      POSTGRES_DB: INC_BPM_PLATFORM
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Desarrollo
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  bmp-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bmp-backend
    ports:
      - "9091:9091"
    depends_on:
      bmp-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://bmp-db:5432/INC_BPM_PLATFORM
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Desarrollo

  bmp-frontend:
    build:
      context: ./portal-angular
      dockerfile: Dockerfile
    container_name: bmp-frontend
    ports:
      - "80:80"
    depends_on:
      - bmp-backend

  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    profiles:
      - n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=America/Guayaquil
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_DATABASE=INC_BPM_PLATFORM
      - DB_POSTGRESDB_HOST=bmp-db
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_USER=postgres
      - DB_POSTGRESDB_PASSWORD=Desarrollo
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      bmp-db:
        condition: service_healthy

volumes:
  pgdata:
  n8n_data:
